{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "list.serviceAccountName" . }}
  labels:
{{ include "list.labels" . | indent 4 }}
{{- end -}}
